apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cb-spider.fullname" . }}-config
  labels:
    {{- include "cb-spider.labels" .  | nindent 4 }}
data:
  grpc_conf.yaml: |-
    {{ range .Files.Lines "files/conf/grpc_conf.yaml" }}
    {{ . }}
    {{ end }}
  log_conf.yaml: |-
    {{ range .Files.Lines "files/conf/log_conf.yaml" }}
    {{ . }}
    {{ end }}
  store_conf.yaml: |-
    {{ range .Files.Lines "files/conf/store_conf.yaml" }}
    {{ . }}
    {{ end }}
  calllog_conf.yaml: |-
    {{ range .Files.Lines "files/conf/calllog_conf.yaml" }}
    {{ . }}
    {{ end }}
