{{- if (eq "manual" .Values.persistence.storageClass) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cb-spider
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/cloud-barista/cb-spider"
{{- end -}}
