apiVersion: v1
kind: Service
metadata:
  name: "cb-spider"
  labels:
    {{- include "cb-spider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}  
  ports:
    - port: {{ .Values.service.restPort }}
      protocol: TCP
      name: rest
      targetPort: 1024
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.restNodePort))) }}
      nodePort: {{ .Values.service.restNodePort }}
{{- end }}
    - port: {{ .Values.service.grpcPort }}
      protocol: TCP
      name: grpc
      targetPort: 2048
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.grpcNodePort))) }}
      nodePort: {{ .Values.service.grpcNodePort }}
{{- end }}
  selector:
    {{- include "cb-spider.selectorLabels" . | nindent 4 }}
