#### Config for cb-dragonfly ####

# influxdb connection info
influxdb:
  endpoint_url: http://cb-dragonfly-influxdb # endpoint for influxDB
  internal_port: 8086
  external_port: 8086
  database: cbmon
  user_name: cbmon
  password: password

# kapacitor connection info
kapacitor:
  endpoint_url: http://cb-dragonfly-kapacitor:9092 # endpoint to kapacitor

# kafka connection info
kafka:
  endpoint_url: cb-dragonfly-kafka
  external_ip: 127.0.0.1 # Cloud-Barista를 설치 및 실행하는 VM/물리머신의 Public IP 주소를 기재
  deploy_type: "compose"    # deploy environment "compose" => docker-compose or others , "helm" => helm chart on k8s
  compose_external_port: 9092
  helm_external_port: 32000
  internal_port: 9092

# collect manager configuration info
collectManager:
  collector_ip: 127.0.0.1  # Cloud-Barista를 설치 및 실행하는 VM/물리머신의 Public IP 주소를 기재
  collector_port: 8094    # udp port
  collector_group_count: 1      # default collector group count

# api server configuration info
apiServer:
  port: 9090

# monitoring interval configuration info
monitoring:
  agent_interval: 2                                 # agent interval (s)
  collector_interval: 10                            # aggregate interval (s)
  max_host_count:  5                                # maximum host count per collector
  monitoring_policy: "agentCount"                   # "agentCount" => The number of agent, "csp" => csp group
  default_policy: "push"                            # push, pull
  puller_interval: 10
  puller_aggregate_interval: 30
  aggregate_type: "avg"                             # min, max, avg, last

grpcServer:
  port: 9999
