@startuml

header **Cloud-Barista Ladybug** (v0.4.0-cafemocha)
title Delete a cluster
hide footbox

participant	"Webtool"		as webtool		#d1e0ff
participant	"Ladybug"		as provider
database	"Ladybug data"	as db
participant	"Tumblebug"		as tumblebug	#d1e0ff


activate webtool
	webtool		->	provider		: DELETE\n/ns/:ns/clusters/:cluster

	activate provider
		provider	->	tumblebug	: GET\n/ns/:ns/mcis/:mcis
		tumblebug	-->	provider	: {mcis}
		alt if mcis does exist 
			provider	->	tumblebug	: DELETE\n/ns/:ns/mcis/:mcis
			tumblebug	-->	provider

			alt if there is an error
				provider	->	tumblebug	: [if it does exist]\nDELETE\n/ns/:ns/mcis/:mcis?action=refine
				tumblebug	-->	provider	: {status}
				
				provider	->	tumblebug	: DELETE\n/ns/:ns/mcis/:mcis
				tumblebug	-->	provider	: {status}
			end

		end

		provider	->	db	: delete
		provider	-->	webtool		: {result}

	deactivate provider

deactivate webtool

@enduml