@@startuml

header **Cloud-Barista Ladybug** (Espresso version)
title Delete a cluster
hide footbox

actor		"User"			as user			#d1e0ff
participant	"Webtool"		as webtool		#d1e0ff
participant	"Ladybug"		as provider
database	"Ladybug data"	as db
participant	"Tumblebug"		as tumblebug	#d1e0ff
participant	"Spider"		as spider		#d1e0ff


user		->	webtool		: delete a cluster

activate webtool
	webtool		->	provider		: DELETE\n/ns/:ns/clusters/:cluster

	activate provider
		provider	->	tumblebug	: GET\n/mcis
		activate tumblebug
			tumblebug	-->	provider 	: ack {mcis}
		deactivate tumblebug

		provider	->	tumblebug	: DELETE\n/mcis
	
		activate tumblebug
			tumblebug	->o	spider		: DELETE\n/vm
			tumblebug	-->	provider 	: ack
		deactivate tumblebug

		provider	->o	db	: delete
		provider		-->	webtool		: ack {result}

	deactivate provider

	webtool	-->	user	: ack {result}
deactivate webtool

@@enduml