@startuml

header **Cloud-Barista Ladybug** (v0.4.0-cafemocha)
title Remove a node
hide footbox

participant	"Webtool"		as webtool		#d1e0ff
participant	"Ladybug"		as provider
database	"Ladybug data"	as db
participant	"Tumblebug"		as tumblebug	#d1e0ff
participant	"Worker nodes"	as wNodes		#eeeeee


activate webtool
	webtool		->	provider		: DELETE\n/ns/:ns/clusters/:cluster/nodes/:node\n

	activate provider

		provider	-->o	db			: select {control-plane}
		provider	->	webtool			: [if there is an error]\nerror

		provider 	->o	wNodes		: drain node (ssh)
		provider	->	webtool		: [if there is an error]\nerror
		provider 	->o	wNodes		: delete node (ssh)
		provider	->	webtool		: [if there is an error]\nerror

		provider	->	tumblebug	: DELETE\n/ns/:ns/mcis/:mcis/vm/:vm
		provider	<--	tumblebug	: {status}
		provider	->	webtool		: [if there is an error]\nerror

		provider	->o	db			: delete {node}
		provider	-->	webtool		: {result}

	deactivate provider

deactivate webtool

@enduml