apiVersion: v1
kind: Service
metadata:
  name: {{ include "cb-restapigw.fullname" . }}
  labels:
    {{- include "cb-restapigw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if (and (eq .Values.service.type "ClusterIP") (not (empty .Values.service.clusterIP))) }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}  
  ports:
    - port: {{ .Values.service.restPort }}
      protocol: TCP
      name: rest
      targetPort: 8000
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.restNodePort))) }}
      nodePort: {{ .Values.service.restNodePort }}
{{- end }}
    - port: {{ .Values.service.webAdminPort }}
      protocol: TCP
      name: webadmin
      targetPort: 8001
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.webAdminNodePort))) }}
      nodePort: {{ .Values.service.webAdminNodePort }}
{{- end }}
  selector:
    {{- include "cb-restapigw.selectorLabels" . | nindent 4 }}
