version: "3.3"
services:

  prometheus-tb:
    image: prom/prometheus
    container_name: etri_prometheus_tb
    user: root
    volumes:
      - ./data/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    ports:
      - "9091:9090"      
    networks:
      - tb-net

  grafana-grpc-tb:
    image: grafana/grafana
    container_name: etri_grpc_grafana_tb
    user: "1000"
    ports:
      - "3101:3000"
    depends_on:
      - prometheus-tb
    env_file:
      - 'env.grafana'
    links:
      - prometheus-tb
    volumes:
      - ./data/grafana-grpc/data:/var/lib/grafana
      - ./data/grafana-grpc/provisioning:/etc/grafana/provisioning
    networks:
      - tb-net      

  jaeger-tb:
    image: jaegertracing/all-in-one:latest
    container_name: etri_jaeger_tb
    ports:
      - "6832:6831/udp"
      - "14269:14268"      
      - "16687:16686"
    networks:
      - tb-net      

networks:
  tb-net: