version: "3.3"
services:
  influxdb:
    image: influxdb:latest
    container_name: cb-restapigw-influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: cb-restapigw-grafana
    user: "1000"
    ports:
      - "3100:3000"
    depends_on:
      - influxdb
    env_file:
      - 'env.grafana'
    links:
      - influxdb
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: cb-restapigw-jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  fake_api:
    image: jaxgeller/lwan
    container_name: fake_api
    volumes:
      - ./data/lwan:/lwan/wwwroot
    ports:
      - "8100:8080"

  fake_api2:
    image: jaxgeller/lwan
    container_name: fake_api2
    volumes:
      - ./data/lwan:/lwan/wwwroot
    ports:
      - "8200:8080"
      
  hmac_site:
    build:
      context: ./web
    container_name: hmac_server
    volumes:
      - ./web/public:/app/public
      - ./web/conf:/app/conf
    ports:
      - "8010:8010"
