{
 "title": "Cloud-Barista",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Node", "query": "label_values(node)" },
   { "name": "NameSpace", "query": "label_values(namespace)" },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\"},container)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
   },
   { "name": "Interval", "query": "2m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "Total Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{node=~\"^$Node$\"}) * 100",
     "legendFormat": "메모리 사용률"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{node=~\"^$Node$\"}) * 100",
     "legendFormat": "메모리 요청률"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{node=~\"^$Node$\"}) * 100",
     "legendFormat": "메모리 제한률"
    }
   ]
  },
  {
   "title": "Cluster cpu usage(2m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[$Interval])) / sum (machine_cpu_cores{node=~\"^$Node$\"}) * 100",
     "legendFormat": "CPU 사용률"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"}) * 100",
     "legendFormat": "CPU 요청률"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"^$Node$\"}) * 100",
     "legendFormat": "CPU 제한률"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$Node$\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{node=~\"^$Node$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[$Interval]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Limts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\"^$Node$\"}) by(namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{}) by(container,namespace)) by(namespace)"
    }
   ]
  },
  {
   "title": "Node Total Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 17, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "POD"
    },
    {
     "expr": "kube_node_status_condition{status=\"true\",node=~\"^$Node$\"}  == 1",
     "legendFormat": "상태"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m])) by (node)",
     "legendFormat": "CPU 사용량"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=~\"^$Node$\"} - 0",
     "legendFormat": "CPU 요청량"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{node=~\"^$Node$\"}) by (node)",
     "legendFormat": "CPU 제한량"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{node=~\"^$Node$\"} - 0",
     "legendFormat": "CPU Total"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "메모리 사용량"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"^$Node$\"}) by (node)",
     "legendFormat": "메모리 요청량"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{node=~\"^$Node$\"}) by (node)",
     "legendFormat": "메모리 제한량"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{node=~\"^$Node$\"} - 0",
     "legendFormat": "메모리 Total"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "디스크 사용량"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "디스크 Total"
    }
   ]
  },
  { "title": "Workload Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "워크로드 상세 정보",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[$Interval])) by (container) / (sum(container_spec_cpu_quota{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/container_spec_cpu_period{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)) * 100",
     "legendFormat": "CPU 사용률"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[$Interval])) by (container)",
     "legendFormat": "CPU 사용량"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "CPU 요청량"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "CPU 제한량"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container=~\"$Container\",container!=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
     "legendFormat": "메모리 사용률(WSS)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "메모리 사용량(WSS)"
    },
    {
     "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
     "legendFormat": "메모리 사용률(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "메모리 사용량(RSS)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "메모리 요청량"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "총 메모리 제한량"
    },
    {
     "expr": "sum(container_fs_usage_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "디스크 사용량"
    },
    {
     "expr": "count(kube_pod_container_info{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container) - 0",
     "legendFormat": "컨테이너 수"
    }
   ]
  }
 ]
}