package tumblebug

// Spec filterling 할 때 수신되는 값
type TbSpecInfo struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	ConnectionName       string `json:"connectionName"`
	CspSpecName          string `json:"cspSpecName"`
	Description          string `json:"description"`
	OsType               string `json:"os_type"`
	AssociatedObjectList string `json:"associatedObjectList"`
	GpuModel             string `json:"gpu_model"`
	GpuP2p               string `json:"gpu_p2p"`

	IsAutoGenerated bool `json:"isAutoGenerated"`

	CostPerHour       float32 `json:"cost_per_hour"`
	EvaluationScore01 float32 `json:"evaluationScore_01"`
	EvaluationScore02 float32 `json:"evaluationScore_02"`
	EvaluationScore03 float32 `json:"evaluationScore_03"`
	EvaluationScore04 float32 `json:"evaluationScore_04"`
	EvaluationScore05 float32 `json:"evaluationScore_05"`
	EvaluationScore06 float32 `json:"evaluationScore_06"`
	EvaluationScore07 float32 `json:"evaluationScore_07"`
	EvaluationScore08 float32 `json:"evaluationScore_08"`
	EvaluationScore09 float32 `json:"evaluationScore_09"`
	EvaluationScore10 float32 `json:"evaluationScore_10"`
	EvaluationStatus  string  `json:"evaluationStatus"`

	EbsBwMbps             int `json:"ebs_bw_Mbps"`
	GpumemGiB             int `json:"gpumem_GiB"`
	MemGiB                int `json:"mem_GiB"`
	MaxNumStorage         int `json:"max_num_storage"`
	MaxTotalStorageTiB    int `json:"max_total_storage_TiB"`
	NetBwGbps             int `json:"net_bw_Gbps"`
	NumCore               int `json:"num_core"`
	NumGpu                int `json:"num_gpu"`
	NumStorage            int `json:"num_storage"`
	NumVCPU               int `json:"num_vCPU"`
	StorageGiB            int `json:"storage_GiB"`
	OrderInFilteredResult int `json:"orderInFilteredResult"`
}
