apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cb-ladybug.fullname" . }}
  labels:
    {{- include "cb-ladybug.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cb-ladybug.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cb-ladybug.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cb-ladybug.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-etcd
          image: darthcabs/tiny-tools:1
          args:
          - /bin/bash
          - -c
          - >
            set -x;
            while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://cloud-barista-etcd:2379/health)" != "200" ]]; do 
              echo '.'
              sleep 15;
            done
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #ports:
          #  - name: http
          #    containerPort: 80
          #    protocol: TCP
          env:
            {{- toYaml .Values.env | nindent 12 }}
          # livenessProbe:
          #   httpGet:
          #     path: /ladybug/
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /ladybug/
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
      {{- if .Values.persistence.enabled }}
          - name: {{ template "cb-ladybug.fullname" . }}
            mountPath: {{ .Values.ladybug.rootPath }}/meta_db
      {{- end }}
          - name: config-volume
            mountPath: {{ .Values.ladybug.rootPath }}/conf
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: {{ template "cb-ladybug.fullname" . }} #cb-ladybug-persistent-storage
        persistentVolumeClaim:
        {{- if .Values.persistence.existingClaim }}
          claimName: {{ .Values.persistence.existingClaim }}
        {{- else }}
          claimName: {{ template "cb-ladybug.fullname" . }}
        {{- end }}
      {{- end }}
      - name: config-volume
        configMap:
          name: {{ include "cb-ladybug.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
