version: "3.3"
services:

  prometheus:
    image: prom/prometheus
    container_name: etri_prometheus
    user: root
    volumes:
      - ./data/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    ports:
      - "9090:9090"      

  grafana-grpc:
    image: grafana/grafana
    container_name: etri_grpc_grafana
    user: "1000"
    ports:
      - "3100:3000"
    depends_on:
      - prometheus
    env_file:
      - 'env.grafana'
    links:
      - prometheus
    volumes:
      - ./data/grafana-grpc/data:/var/lib/grafana
      - ./data/grafana-grpc/provisioning:/etc/grafana/provisioning

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: etri_jaeger
    ports:
      - "6831:6831/udp"
      - "14268:14268"      
      - "16686:16686"
