apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cb-dragonfly.serviceAccountName" . }}
  labels:
    {{- include "cb-dragonfly.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cb-dragonfly.clusterRoleName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cb-dragonfly.roleBindingName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cb-dragonfly.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cb-dragonfly.serviceAccountName" . }}
