apiVersion: v2
name: cloud-barista
description: Cloud-Barista Helm chart
type: application
version: 0.6.0
appVersion: 0.6.0
dependencies:
  - name: cb-dragonfly
    version: 0.6.0
    condition: cb-dragonfly.enabled
  - name: cb-restapigw
    version: 0.5.0
    condition: cb-restapigw.enabled
  - name: cb-spider
    version: 0.6.0
    condition: cb-spider.enabled
  - name: cb-tumblebug
    version: 0.6.0
    condition: cb-tumblebug.enabled
  - name: cb-mcks
    version: 0.6.0
    condition: cb-mcks.enabled
  - name: cb-ladybug
    version: 0.6.0
    condition: cb-ladybug.enabled
  - name: cb-webtool
    version: 0.6.0
    condition: cb-webtool.enabled
  # - name: docker-registry
  #   version: ~1.9.3
  #   repository: "https://charts.helm.sh/stable"
  #   condition: docker-registry.enabled
  # - name: weave-scope
  #   version: ~1.1.10
  #   repository: "https://charts.helm.sh/stable"
  #   condition: weave-scope.enabled
  - name: grafana
    version: ~6.6.4
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: prometheus
    version: ~11.16.3
    repository: "https://prometheus-community.github.io/helm-charts/"
    condition: prometheus.enabled
  - name: etcd
    version: ~6.2.9
    condition: etcd.enabled
    repository: "https://charts.bitnami.com/bitnami"
