version: "3.3"
services:

  # InfluxDB for CB-Dragonfly
  cb-dragonfly-influxdb:
    image: influxdb:1.8-alpine
    container_name: cb-dragonfly-influxdb
    ports:
      - 28086:8086
      - 28088:8088
    environment:
      - PRE_CREATE_DB=cbmon
      - INFLUXDB_DB=cbmon
      - INFLUXDB_ADMIN_USER=cbmon
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: always

  # Kapacitor for CB-Dragonfly
  cb-dragonfly-kapacitor:
    image: kapacitor:1.5
    container_name: cb-dragonfly-kapacitor
    ports:
      - 29092:9092
    environment:
      - KAPACITOR_HOSTNAME=cb-dragonfly-kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://cb-dragonfly-influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=cbmon
      - KAPACITOR_INFLUXDB_0_PASSWORD=password
    depends_on:
      - cb-dragonfly-influxdb
    restart: always

  # Chronograf for CB-Dragonfly
  cb-dragonfly-chronograf:
    image: chronograf:1.8.4-alpine
    container_name: cb-dragonfly-chronograf
    ports:
      - 8888:8888
    command:
      - --influxdb-url=http://cb-dragonfly-influxdb:8086
      - --influxdb-username=cbmon
      - --influxdb-password=password
      - --kapacitor-url=http://cb-dragonfly-kapacitor:9092
      - --kapacitor-username=cbmon
      - --kapacitor-password=password
    depends_on:
      - cb-dragonfly-influxdb
      - cb-dragonfly-kapacitor

  # Zookeeper for CB-Dragonfly
  cb-dragonfly-zookeeper:
    image: wurstmeister/zookeeper
    container_name: cb-dragonfly-zookeeper
    ports:
      - 2181:2181
    restart: always

  # Kafka for CB-Dragonfly
  cb-dragonfly-kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: cb-dragonfly-kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: cb-dragonfly-kafka
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: cb-dragonfly-zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 1
      # 1 hours (delete logs)
      KAFKA_LOG_RETENTION_BYTES: 524288000
      # 500 MB
      KAFKA_LOG_SEGMENT_BYTES: 262144000
      # 250 MB
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 600000
      # 10 min (check interval)
      KAFKA_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9092:9092
    restart: always
