version: "3.3"
services:

  # CB-Dragonfly
  cb-dragonfly:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudbaristaorg/cb-dragonfly:espresso-v0.1-kafka
    container_name: cb-dragonfly
    volumes:
      - ./conf:/go/src/github.com/cloud-barista/cb-dragonfly/conf
      - ./log:/go/src/github.com/cloud-barista/cb-dragonfly/log
    ports:
      - 9090:9090
      - 9999:9999
    depends_on:
      - cb-dragonfly-zookeeper
      - cb-dragonfly-kafka
      - cb-dragonfly-influxdb
      - cb-dragonfly-kapacitor
    environment:
      - CBSTORE_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBLOG_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
      - CBMON_ROOT=/go/src/github.com/cloud-barista/cb-dragonfly
    restart: always
    security_opt:
      - no-new-privileges
#    extra_hosts:
#      - "external-cb-dragonfly:192.168.130.7"
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly

  # zookeeper for CB-Dragonfly
  cb-dragonfly-zookeeper:
    image: wurstmeister/zookeeper
    container_name: cb-dragonfly-zookeeper
    ports:
      - 2181:2181
    restart: always
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly-zookeeper

  # etcd for CB-Dragonfly
  cb-dragonfly-kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    container_name: cb-dragonfly-kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: cb-dragonfly-kafka
      KAFKA_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: cb-dragonfly-zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LOG_RETENTION_MS: 10000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
      KAFKA_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9092:9092
    restart: always
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly-kafka
#    extra_hosts:
#      - "external-cb-dragonfly:192.168.130.7"

  # InfluxDB for CB-Dragonfly
  cb-dragonfly-influxdb:
    image: influxdb:1.8-alpine
    container_name: cb-dragonfly-influxdb
    ports:
      - 28083:8083
      - 28086:8086
    environment:
      - PRE_CREATE_DB=cbmon
      - INFLUXDB_DB=cbmon
      - INFLUXDB_ADMIN_USER=cbmon
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: always
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly-influxdb

  # Kapacitor for CB-Dragonfly
  cb-dragonfly-kapacitor:
    image: kapacitor:1.5
    container_name: cb-dragonfly-kapacitor
    ports:
      - 29092:9092
    environment:
      - KAPACITOR_HOSTNAME=cb-dragonfly-kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://cb-dragonfly-influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=cbmon
      - KAPACITOR_INFLUXDB_0_PASSWORD=password
    depends_on:
      - cb-dragonfly-influxdb
    restart: always
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly-kapacitor

  # Chronograf for CB-Dragonfly
  cb-dragonfly-chronograf:
    image: chronograf:1.8.4-alpine
    container_name: cb-dragonfly-chronograf
    ports:
      - 8888:8888
    command:
      - --influxdb-url=http://cb-dragonfly-influxdb:8086
      - --influxdb-username=cbmon
      - --influxdb-password=password
      - --kapacitor-url=http://cb-dragonfly-kapacitor:9092
      - --kapacitor-username=cbmon
      - --kapacitor-password=password
    depends_on:
      - cb-dragonfly-zookeeper
      - cb-dragonfly-kafka
      - cb-dragonfly-influxdb
      - cb-dragonfly-kapacitor
      - cb-dragonfly
    networks:
      cb-dragonfly:
        aliases:
          - cb-dragonfly-chronograf

#  cb-dragonfly-zk-web:
#    image: goodguide/zk-web
#    container_name: cb-dragonfly-zk-web
#    ports:
#      - "8080:8080"
#    environment:
#      - ZKWEB_PORT=8080
#      - ZKWEB_CREDENTIALS=admin:hello
#    networks:
#      cb-dragonfly:
#        aliases:
#          - cb-dragonfly-zk-web

networks:
  cb-dragonfly: