replicaCount: 1

image:
  repository: cloudbaristaorg/cb-webtool
  pullPolicy: Always

env:
  - name: CBWS_TARGET
    value: ""
  - name: API_GW
    value: "http://cb-restapigw:8000"
  - name: SPIDER_URL
    value: "http://cb-spider:1234/spider"
  - name: TUMBLE_URL
    value: "http://cb-tumblebug:1323/tumblebug"
  - name: MCKS_URL
    value: "http://cb-mcks:1470/mcks"
  - name: LADYBUG_URL
    value: "http://cb-ladybug:1592/ladybug"
  - name: DRAGONFLY_URL
    value: "http://cb-dragonfly:9090/dragonfly"
  - name: LoginUser
    value: "admin"
  - name: LoginEmail
    value: "admin"
  - name: LoginPassword
    value: "admin"
  - name: LoginAccessSecret
    value: "cloudbarista"
  - name: LoginRefreshSecret
    value: "webtool"
  - name: API_USERNAME
    value: "default"
  - name: API_PASSWORD
    value: "default"
  


imagePullSecrets: []
nameOverride: ""
fullnameOverride: "cb-webtool"

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 1234

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: cloud-barista.local
      paths: ["/*"]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

