definitions:
  - name: Splash RateLimit Test
    active: true
    hosts:
      - host: http://fake_api:8100
        weight: 3
      - host: http://fake_api2:8200
        weight: 5
    endpoint: "/splash_ratelimit"
    except_querystrings:
      - "name"
      - "querystring"
    except_headers:
      - "Testing"
    middleware:
      mw-ratelimit:
        max_rate: 5
        client_max_rate: 10
        strategy: "ip" #header #ip
        key: "" #"X-Private-Token"
    backend:
      - url_pattern: "/shop/campaigns.json"
        whitelist:
          - "campaigns"
        lb_mode: wrr
      - url_pattern: "/shop/products.json"
        middleware:
          mw-proxy:
            flatmap_filter:
              - type: "move"
                args:
                  - "products.*.id"
                  - "products.*.id-"
              - type: "del"
                args:
                  - "products.*.image"
                  - "products.*.body_html"
                  - "products.*.created_at"
                  - "products.*.handle"
                  - "products.*.product_type"
                  - "products.*.published_at"
                  - "products.*.published_scope"
                  - "products.*.tags"
                  - "products.*.template_suffix"
                  - "products.*.updated_at"
                  - "products.*.vendor"
          mw-ratelimit:
            max_rate: 1
            capacity: 1
        lb_mode: rr
  - name: Splash Test
    active: true
    endpoint: "/splash"
    hosts:
      - host: http://fake_api:8100
        weight: 0
      - host: http://fake_api2:8200
        weight: 0
    backend:
      - hosts:
          - host: http://fake_api:8100
            weight: 3
          - host: http://fake_api2:8200
            weight: 5
        url_pattern: /shop/campaigns.json
        whitelist:
          - campaigns
        middleware:
          mw-proxy:
            flatmap_filter:
              - args:
                  - campaigns.*.discounts
                type: del
        lb_mode: wrr
      - hosts:
        url_pattern: /shop/products.json
        middleware:
          mw-proxy:
            flatmap_filter:
              - args:
                  - products.*.id
                  - products.*.id-
                type: move
              - args:
                  - products.*.image
                  - products.*.body_html
                  - products.*.created_at
                  - products.*.handle
                  - products.*.product_type
                  - products.*.published_at
                  - products.*.published_scope
                  - products.*.tags
                  - products.*.template_suffix
                  - products.*.updated_at
                  - products.*.vendor
                type: del
        lb_mode: rr
  - name: Sequential Test
    active: true
    endpoint: /sequential
    hosts:
      - host: http://fake_api:8100
        weight: 0
    middleware:
      mw-proxy:
        sequential: true
    backend:
      - url_pattern: /hotels/1.json
        whitelist:
          - destination_id
      - url_pattern: /destinations/{{.Resp0_destination_id}}.json
        middleware:
          mw-http:
            return_error_details: sequential
  - name: Fail Test
    active: true
    endpoint: /fail
    backend:
      - hosts:
          - host: http://fake_api:8100
            weight: 0
        url_pattern: /user/1.json
        group: user
        target: address
      - hosts:
          - host: http://fake_url_that_should_not_resolve.tld
            weight: 0
        url_pattern: /
        group: none
  - name: Public Test
    active: true
    endpoint: /public
    timeout: 100m
    backend:
      - hosts:
          - host: https://api.github.com
            weight: 0
        url_pattern: /users/ccambo
        group: github
        whitelist:
          - avatar_url
          - name
          - company
          - blog
          - location
          - mail
          - hireable
          - followers
          - public_repos
          - public_gists
        mapping:
          blog: website
        middleware:
          mw-httpcache:
            enabled: true
      - hosts:
          - host: https://api.bitbucket.org
            weight: 0
        url_pattern: /2.0/users/kpacha
        group: bitbucket
        whitelist:
          - links.avatar
          - display_name
          - website
          - location
        mapping:
          display_name: name
        middleware:
          mw-http:
            return_error_details: fail_1
  - name: Error Test
    active: true
    endpoint: /errortest
    hosts:
      - host: http://fake_api:8100
        weight: 0
    backend:
      - url_pattern: /user/1.json
        group: user
        target: address
        middleware:
          mw-http:
            return_error_details: error_1
      - url_pattern: /user/2.json
        group: user2
        target: address
        middleware:
          mw-http:
            return_error_details: error_2
  - name: External(Github) Test
    active: true
    endpoint: /github/:user
    backend:
      - hosts:
          - host: https://api.github.com
            weight: 0
        url_pattern: /users/{{.User}}
        disable_host_sanitize: true
  - name: Collection Test
    active: true
    endpoint: /collection
    hosts:
      - host: http://fake_api:8100
        weight: 0
    backend:
      - url_pattern: /destinations/2.json
        mapping:
          collection: data
        is_collection: true
        wrap_collection_to_json: true
  - name: Custom Test
    active: true
    endpoint: /private/custom
    hosts:
      - host: http://fake_api:8100
        weight: 0
    middleware:
      mw-auth:
        access_ids:
          - etri
        secure_key: "###TEST_SECURE_KEY###"
    backend:
      - url_pattern: /user/1.json
  - name: Error with Data Test
    active: true
    endpoint: /errordata
    hosts:
      - host: http://localhost:8010
        weight: 0
    backend:
      - url_pattern: /error/500
        middleware:
          mw-http:
            return_error_details: "err"
        group: data
      - hosts:
          - host: http://fake_api:8100
            weight: 3
          - host: http://fake_api2:8200
            weight: 5
        url_pattern: /shop/campaigns.json
        group: campaigns
  - name: Error with Data on ByPass Test
    active: true
    endpoint: /error/*bypass
    hosts:
      - host: http://localhost:8010
        weight: 0
    backend:
      - url_pattern: /*bypass
        middleware:
          mw-http:
            return_error_details: "err"
