definitions:
  - name: Order Service
    active: true
    endpoint: /order/*bypass
    backend:
      - hosts:
          - host: http://localhost:8400
            weight: 0
        url_pattern: /*bypass
  - name: Inventory Service
    active: true
    endpoint: /inventory/*bypass
    backend:
      - hosts:
          - host: http://localhost:8500
            weight: 0
        url_pattern: /*bypass
        