// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://cloud-barista.github.io",
            "email": "contact-to-cloud-barista@googlegroups.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agent": {
            "post": {
                "description": "모니터링 에이전트 설치",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Agent] Monitoring Agent"
                ],
                "summary": "Install agent to vm",
                "parameters": [
                    {
                        "description": "Details for an Agent Install object",
                        "name": "agentInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.AgentType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "모니터링 에이전트 제거",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Agent] Monitoring Agent"
                ],
                "summary": "Uninstall agent to vm",
                "parameters": [
                    {
                        "description": "Details for an Agent Remove object",
                        "name": "agentInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.AgentType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/agent/metadata": {
            "get": {
                "description": "에이전트 메타데이터 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Agent] Monitoring Agent"
                ],
                "summary": "List agent metadata",
                "parameters": [
                    {
                        "enum": [
                            "test_ns"
                        ],
                        "type": "string",
                        "description": "네임스페이스 아이디",
                        "name": "ns",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "test_mcis"
                        ],
                        "type": "string",
                        "description": "MCIS 아이디",
                        "name": "mcisId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "test_vm"
                        ],
                        "type": "string",
                        "description": "VM 아이디",
                        "name": "vmId",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "aws"
                        ],
                        "type": "string",
                        "description": "VM의 CSP 정보",
                        "name": "cspType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Different return structures by the given param",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.JSONResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "[DEFAULT]": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/agent.MetaDataListType"
                                            }
                                        },
                                        "[ID]": {
                                            "$ref": "#/definitions/agent.AgentInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/eventhandler": {
            "post": {
                "description": "알람 이벤트 핸들러 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[EventHandler] Alarm Event Handler management"
                ],
                "summary": "Create monitoring alert event-handler",
                "parameters": [
                    {
                        "description": "Details for an EventHandler object",
                        "name": "eventHandlerInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventHandlerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventHandler"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/eventhandler/type/{type}/event/{name}": {
            "get": {
                "description": "알람 이벤트 핸들러 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[EventHandler] Alarm Event Handler management"
                ],
                "summary": "Get monitoring alert event-handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 유형",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventHandler"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "알람 이벤트 핸들러 수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[EventHandler] Alarm Event Handler management"
                ],
                "summary": "Update monitoring alert event-handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 유형",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Details for an EventHandler (slack) object",
                        "name": "eventHandlerInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventHandlerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventHandler"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "알람 이벤트 핸들러 삭제",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[EventHandler] Alarm Event Handler management"
                ],
                "summary": "Delete monitoring alert event-handler",
                "parameters": [
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 유형",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "이벤트 핸들러 이름",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/eventhandlers": {
            "get": {
                "description": "알람 이벤트 핸들러 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[EventHandler] Alarm Event Handler management"
                ],
                "summary": "List monitoring alert event-handler",
                "parameters": [
                    {
                        "enum": [
                            "slack",
                            "smtp"
                        ],
                        "type": "string",
                        "description": "이벤트 핸들러 유형",
                        "name": "eventType",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.AlertEventHandler"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/task": {
            "post": {
                "description": "알람 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Alarm] Alarm management"
                ],
                "summary": "Create monitoring alert",
                "parameters": [
                    {
                        "description": "Details for an Event object",
                        "name": "eventHandlerInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AlertTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertTask"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/task/{task_id}": {
            "get": {
                "description": "알람 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Alarm] Alarm management"
                ],
                "summary": "Get monitoring alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "태스크 아이디",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertTask"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "알람 수정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Alarm] Alarm management"
                ],
                "summary": "Update monitoring alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "태스크 아이디",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Details for an Event object",
                        "name": "eventHandlerInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.AlertTask"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertTask"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "delete": {
                "description": "알람 삭제",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Alarm] Alarm management"
                ],
                "summary": "Delete monitoring alert",
                "parameters": [
                    {
                        "type": "string",
                        "description": "태스크 아이디",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/task/{task_id}/events": {
            "get": {
                "description": "알람 로그 정보 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Log] Alarm Event Log"
                ],
                "summary": "List monitoring alert event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "태스크 아이디",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.AlertEventLog"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/alert/tasks": {
            "get": {
                "description": "알람 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Alarm] Alarm management"
                ],
                "summary": "List monitoring alert",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/types.AlertTask"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/config": {
            "get": {
                "description": "모니터링 정책 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Setting] Multi-Cloud Monitor Policy Setting"
                ],
                "summary": "Get monitoring config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Monitoring"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            },
            "put": {
                "description": "모니터링 정책 설정",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Setting] Multi-Cloud Monitor Policy Setting"
                ],
                "summary": "Set monitoring config",
                "parameters": [
                    {
                        "description": "Details for an Monitor object",
                        "name": "monitorInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/config.Monitoring"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Monitoring"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/config/reset": {
            "put": {
                "description": "모니터링 정책 초기화",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Setting] Multi-Cloud Monitor Policy Setting"
                ],
                "summary": "Reset monitoring config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/config.Monitoring"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "서버 헬스체크",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Health] Health Check"
                ],
                "summary": "Server Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{ns_id}/mcis/{mcis_id}/vm/{vm_id}/agent_ip/{agent_ip}/mcis_metric/{metric_name}/mcis-monitoring-info": {
            "get": {
                "description": "멀티 클라우드 인프라 VM 온디맨드 모니터링 정보 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Monitoring] Monitoring management"
                ],
                "summary": "Get MCIS on-demand monitoring metric info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "네임스페이스 아이디",
                        "name": "ns_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MCIS 아이디",
                        "name": "mcis_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "VM 아이디",
                        "name": "vm_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "에이전트 아이피",
                        "name": "agent_ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "메트릭 정보",
                        "name": "metric_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Different return structures by the given param",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.JSONResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "[DEFAULT]": {
                                            "$ref": "#/definitions/metric.CBMCISMetric"
                                        },
                                        "[Mrtt]": {
                                            "$ref": "#/definitions/metric.MCBMCISMetric"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{ns_id}/mcis/{mcis_id}/vm/{vm_id}/metric/{metric_name}/info": {
            "get": {
                "description": "멀티 클라우드 인프라 VM 모니터링 정보 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Monitoring] Monitoring management"
                ],
                "summary": "Get vm monitoring info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "네임스페이스 아이디",
                        "name": "ns_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MCIS 아이디",
                        "name": "mcis_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "VM 아이디",
                        "name": "vm_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "메트릭 정보",
                        "name": "metric_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "m",
                            "h",
                            "d"
                        ],
                        "type": "string",
                        "description": "모니터링 단위",
                        "name": "periodType",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "min",
                            "max",
                            "avg",
                            "last"
                        ],
                        "type": "string",
                        "description": "모니터링 통계 기준",
                        "name": "statisticsCriteria",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "5m",
                            "5h",
                            "5d"
                        ],
                        "type": "string",
                        "description": "모니터링 조회 범위",
                        "name": "duration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.VMMonInfoType"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        },
        "/ns/{ns}/mcis/{mcis_id}/vm/{vm_id}/agent_ip/{agent_ip}/metric/{metric_name}/ondemand-monitoring-info": {
            "get": {
                "description": "멀티 클라우드 인프라 VM 온디맨드 모니터링 정보 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "[Monitoring] Monitoring management"
                ],
                "summary": "Get vm on-demand monitoring metric info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "네임스페이스 아이디",
                        "name": "ns",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "MCIS 아이디",
                        "name": "mcis_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "VM 아이디",
                        "name": "vm_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "에이전트 아이피",
                        "name": "agent_ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "메트릭 정보",
                        "name": "metric_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.VMOnDemandMetricType"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.SimpleMsg"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agent.AgentInfo": {
            "type": "object",
            "properties": {
                "agent_health": {
                    "type": "string"
                },
                "agent_state": {
                    "type": "string"
                },
                "agent_type": {
                    "type": "string"
                },
                "agent_unhealthy_resp_cnt": {
                    "type": "integer"
                },
                "csp_type": {
                    "type": "string"
                },
                "mcis_id": {
                    "type": "string"
                },
                "ns_id": {
                    "type": "string"
                },
                "public_ip": {
                    "type": "string"
                },
                "vm_id": {
                    "type": "string"
                }
            }
        },
        "agent.MetaDataListType": {
            "type": "object",
            "properties": {
                "id(ns_id/mcis_id/vm_id/csp_type)": {
                    "$ref": "#/definitions/agent.AgentInfo"
                }
            }
        },
        "config.Monitoring": {
            "type": "object",
            "properties": {
                "agent_interval": {
                    "description": "모니터링 에이전트 수집주기",
                    "type": "integer"
                },
                "aggregate_type": {
                    "type": "string"
                },
                "collector_interval": {
                    "description": "모니터링 콜렉터 Aggregate 주기",
                    "type": "integer"
                },
                "default_policy": {
                    "description": "모니터링 기본 정책",
                    "type": "string"
                },
                "deploy_type": {
                    "type": "string"
                },
                "max_host_count": {
                    "description": "모니터링 콜렉터 수",
                    "type": "integer"
                },
                "monitoring_policy": {
                    "description": "모니터링 콜렉터 정책",
                    "type": "string"
                },
                "puller_aggregate_interval": {
                    "type": "integer"
                },
                "puller_interval": {
                    "description": "모니터링 puller 실행 주기",
                    "type": "integer"
                }
            }
        },
        "metric.CBMCISMetric": {
            "type": "object",
            "properties": {
                "desc": {
                    "type": "string"
                },
                "elapsed": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "specid": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "metric.MCBMCISMetric": {
            "type": "object",
            "properties": {
                "resultarray": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/metric.CBMCISMetric"
                    }
                }
            }
        },
        "rest.AgentType": {
            "type": "object",
            "properties": {
                "cspType": {
                    "type": "string"
                },
                "mcis_id": {
                    "type": "string"
                },
                "ns_id": {
                    "type": "string"
                },
                "port": {
                    "type": "string"
                },
                "public_ip": {
                    "type": "string"
                },
                "ssh_key": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                },
                "vm_id": {
                    "type": "string"
                }
            }
        },
        "rest.JSONResult": {
            "type": "object"
        },
        "rest.SimpleMsg": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Any message"
                }
            }
        },
        "rest.VMMonInfoTags": {
            "type": "object",
            "properties": {
                "host_id": {
                    "type": "string"
                }
            }
        },
        "rest.VMMonInfoType": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "tags": {
                    "$ref": "#/definitions/rest.VMMonInfoTags"
                },
                "time": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.VMMonInfoValues"
                    }
                }
            }
        },
        "rest.VMMonInfoValues": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "read_bytes": {
                    "type": "number"
                },
                "read_time": {
                    "type": "number"
                },
                "reads": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                },
                "used_percent": {
                    "type": "number"
                },
                "write_bytes": {
                    "type": "number"
                },
                "write_time": {
                    "type": "number"
                },
                "writes": {
                    "type": "number"
                }
            }
        },
        "rest.VMOnDemandMetricTags": {
            "type": "object",
            "properties": {
                "mcis_id": {
                    "type": "string"
                },
                "ns_id": {
                    "type": "string"
                },
                "vm_id": {
                    "type": "string"
                }
            }
        },
        "rest.VMOnDemandMetricType": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.VMOnDemandMetricTags"
                    }
                },
                "time": {
                    "type": "string"
                },
                "values": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.VMOnDemandMetricValues"
                    }
                }
            }
        },
        "rest.VMOnDemandMetricValues": {
            "type": "object",
            "properties": {
                "bytes_in": {
                    "type": "string"
                },
                "bytes_out": {
                    "type": "string"
                },
                "pkts_in": {
                    "type": "string"
                }
            }
        },
        "types.AlertEventHandler": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "options": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.AlertEventHandlerReq": {
            "type": "object",
            "properties": {
                "channel": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "host": {
                    "description": "Parameters for SMTP",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "description": "Parameters for Slack",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "workspace": {
                    "type": "string"
                }
            }
        },
        "types.AlertEventLog": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "types.AlertTask": {
            "type": "object",
            "properties": {
                "alert_event_message": {
                    "type": "string"
                },
                "alert_event_name": {
                    "type": "string"
                },
                "alert_event_type": {
                    "type": "string"
                },
                "alert_math_expression": {
                    "type": "string"
                },
                "alert_threshold": {
                    "type": "number"
                },
                "critic_event_cnt": {
                    "type": "integer"
                },
                "event_duration": {
                    "type": "string"
                },
                "measurement": {
                    "type": "string"
                },
                "metric": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "target_id": {
                    "type": "string"
                },
                "target_type": {
                    "type": "string"
                },
                "warn_event_cnt": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9090",
	BasePath:    "/dragonfly",
	Schemes:     []string{},
	Title:       "CB-Dragonfly REST API",
	Description: "CB-Dragonfly REST API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
