package mcir

import (
	tbcommon "github.com/cloud-barista/cb-webtool/src/model/tumblebug/common"
)

type TbSecurityGroupInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	ConnectionName       string                   `json:"connectionName"`
	CspSecurityGroupId   string                   `json:"cspSecurityGroupId"`
	CspSecurityGroupName string                   `json:"cspSecurityGroupName"`
	Description          string                   `json:"description"`
	FirewallRules        []TbFirewallRuleInfo     `json:"firewallRules"`
	ID                   string                   `json:"id"`
	IsAutoGenerated      string                   `json:"isAutoGenerated"`

	KeyValueList []tbcommon.TbKeyValue `json:"keyValueList"`
	Name         string                `json:"name"`
	SystemLabel  string                `json:"systemLabel"`
	VNetID       string                `json:"vNetId"`
}

type TbSecurityGroupInfos []TbSecurityGroupInfo
