package mcir

import (
	tbcommon "github.com/cloud-barista/cb-webtool/src/model/tumblebug/common"
)

type TbVNetInfo struct {
	AssociatedObjectList []string `json:"associatedObjectList"`

	CidrBlock      string `json:"cidrBlock"`
	ConnectionName string `json:"connectionName"`
	CspVNetID      string `json:"cspVNetId"`
	CspVNetName    string `json:"cspVNetName"`

	Description     string                `json:"description"`
	ID              string                `json:"id"`
	IsAutoGenerated bool                  `json:"isAutoGenerated"`
	KeyValueInfos   []tbcommon.TbKeyValue `json:"keyValueList"`

	Name           string         `json:"name"`
	Statue         string         `json:"status"`
	SubnetInfoList []TbSubnetInfo `json:"subnetInfoList"`
	SystemLabel    string         `json:"systemLabel"`
}

type TbVNetInfos []TbVNetInfo
