version: 1
grpc:
  ladybugsrv:
    addr: :50256
    #reflection: enable
    #tls:
    #  tls_cert: $APP_ROOT/certs/server.crt
    #  tls_key: $APP_ROOT/certs/server.key
    interceptors:
      #auth_jwt:
      #  jwt_key: your_secret_key
      prometheus_metrics:
        listen_port: 9095
      opentracing:
        jaeger:
          endpoint: localhost:6834
          service_name: ladybug grpc server
          sample_rate: 1
          